### ISSUE TITLE
New line?

### ISSUE THREAD

**Issue by boczkas** [totine/java-academy--tic-tac-toe#18]
It would be nice to have new line between last user entry and board print

x and y must be between 3 and 100
For example: 4 5 3 
or press ENTER to play standard OX game with 3x3 board"
5 5 3
    1 | 2 | 3 | 4 | 5   
  ---------------------  
1|| 1 | 2 | 3 | 4 | 5 ||1
2|| 6 | 7 | 8 | 9 | 10||2
3|| 11| 12| 13| 14| 15||3
4|| 16| 17| 18| 19| 20||4
5|| 21| 22| 23| 24| 25||5
  ---------------------  
    1 | 2 | 3 | 4 | 5

**Comment by totine** [comment]
fixed
